name: CI/CD Pipeline

# Akcja zostanie uruchomiona, gdy zaktualizujesz branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Klonowanie kodu z repozytorium
    - uses: actions/checkout@v2

    # 2. Instalowanie Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Wersja Node.js (możesz zmienić na swoją wersję)

    # 3. Instalowanie zależności
    - name: Install dependencies
      run: npm install

    # 4. Uruchamianie testów
    - name: Run tests
      run: npm test  # Zakładam, że masz testy w projekcie, jeśli nie, usuń ten krok

    # 5. Budowanie projektu
    - name: Build
      run: npm run build

    # 6. Wdrożenie na Vercel (lub inny hosting)
    - name: Deploy to Vercel
      run: vercel --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Zmienne środowiskowe dla Vercel
